query($slug: String!){
  product: productBySlug(slug: $slug){
    id
    name
    price
    sale_price
    description
    Brand{
      id
      name
      slug
    }
    Images{
      id
      image
    }
  }
}
